### ISSUE TITLE
Interacting with a multiple subdomain LDAP

### ISSUE THREAD

**Issue by christophe-lejeune** [Hypertopic/AAAforREST#58]
Thank you very much for the great work done on AAAforREST !

I would like to use it with my university's LDAP. My first attempt was successful. That'a already great ! 

However, I realized that my LDAP have "subdomains" for different types of students. In the example provided in `conf/config.yml`, we would have two different search bases, one with `dc=example,dc=com` and the other with `dc=master,dc=example,dc=com`. Each configuration works if it is used alone. But I fail to use it altogether.  

As you can see, the search bases have `dc=example,dc=com` in common. Unfortunately, queries on `dc=example,dc=com` gives no answer concerning `dc=master,dc=example,dc=com`. Do you think it would be possible to generate "recursive" queries to this LDAP ? Or should we consider these two search bases as two different LDAP, as in first version of AAAforREST ?

I would be happy to conduct tests under your direction. 

Again many thanks and best wishes !

**Comment by benel** [comment]
The `scope` is a an option of [ldap.js `search`](http://ldapjs.org/client.html#search). By default, is is set to `base` but could be set to `sub`. It is called from our `Ldap` module in the method [`searchAndBind`](https://github.com/Hypertopic/AAAforREST/blob/master/app/ldap.js#L27). 
The new scope could be hard coded, or (preferably) changed in the config file.

**Comment by benel** [comment]
I suggest to have the scope hard coded with `sub` BUT also that administrators would use the greatest common search path (e.g. : `ou=people,dc=acme,dc=edu` for classic AD-like directory and `dc=acme,dc=edu` for a directory with multiple subtrees).

**Comment by benel** [comment]
`searchAndBind` has two steps: `search` and `bind`. 

`search` can be applied recursively from any broader node.
`bind` must be applied to the exact node.

@christophe-lejeune I will share a small node program so that you can check that your LDAP server is able to generate on first step the input needed in the second step.

**Comment by benel** [comment]
Testable on any computer that can connect to your LDAP server and on which you can have Node.js installed.

In a new folder.

Copy-paste in a new file `package.json`:

```json
{
  "name": "ldaptest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "ldapjs": "^2.3.1",
    "minimist": "^1.2.5"
  }
}
```

Copy-paste in a new file named `index.js`:

```js
const LDAP = require("ldapjs");
const {filter, url, searchBase} = require('minimist')(process.argv.slice(2));

let close = (ldap) => {
  if (ldap._socket) {
    ldap._socket.end()
  }
}

let ldap = LDAP.createClient({url});
ldap.search(searchBase, {scope: 'sub', filter, attributes: ['dn']}, (tcpError, res) => {
    if (tcpError) {
        close(ldap);
        console.log('TCP error');
    } else {
        res.on('error', () => {
          close(ldap);
          console.log('User not found');
        });
        res.on('searchEntry', (entry) => {
          close(ldap);
          console.log(entry.object.dn);
        });
    }
  }
);
```

Install dependencies:
```shell
npm install
```

Launch the program to test your LDAP server ability to search for the complete path ("distinguished name") of a user from his/her ID : 

```shell
node index.js --url ldap://ldap.acme.fr --searchBase dc=acme,dc=fr --filter uid=benel  
```

You'll get for example: 
```ini
uid=benel,ou=people,dc=acme,dc=fr
```

Test it on IDs of people with different status.

**Comment by christophe-lejeune** [comment]
Dear @benel 

Thank you very much for this node program, super easy to deploy within seconds on a test machine. 

The issues of this test seems to confirm that the my university's LDAP accepts "recursive" requests 

Indeed, it have results with id belonging to different status:

```
uid=lejeune,ou=people,dc=master,dc=acme,dc=fr
uid=benel,ou=people,dc=acme,dc=fr
```
Are these results sufficient to make a try with `scope: "sub"` or does the two steps (`search` and `bind`) require additional developments prior to make such tests.

Again many thank for your helps in deploying/adapting AAAforREST for my needs !

**Comment by benel** [comment]
> Are these results sufficient to make a try with scope: "sub" or does the two steps (search and bind) require additional developments prior to make such tests.

Additional (small)) developments are necessary to inject the resulted DN into the bind.

**Comment by benel** [comment]
And here is a new version that searches AND binds:

```js
const LDAP = require("ldapjs");
const {filter, url, searchBase, password} = require('minimist')(process.argv.slice(2));

let close = (ldap) => {
  if (ldap._socket) {
    ldap._socket.end()
  }
}

let ldap = LDAP.createClient({url});

ldap.search(searchBase, {scope: 'sub', filter, attributes: ['dn']}, (tcpError, res) => {
    if (tcpError) {
        close(ldap);
        console.log('TCP error');
    } else {
        let dn;
        res.on('searchEntry', (entry) => {
          dn = entry.object.dn;
        });
        res.on('end', () => {
          console.log({dn});
          ldap.bind(dn, password, (badPassword) => {
            close(ldap);
            console.log({logged: !badPassword});
          });
        });
      }
});
```

```shell
node index.js --url ldap://ldap.acme.fr --searchBase dc=acme,dc=fr --filter uid=benel  --password "p8ssW0rd"
```

```js
{ dn: 'uid=benel,ou=people,dc=acme,dc=fr' }
{ logged: true }
```

**Comment by christophe-lejeune** [comment]
I confirm the messages are different when the id and the password matches `{ logged: true }`, when the password does not match the id `{ logged: false }` and when the id does not belong to the ldap `{ dn: undefined }`. 

In the latter case, an exception is raised, but if does not invalidate the test.

**Comment by benel** [comment]
I published a temporary container image named "aaaforrest:dev". If you have time to test it, please tell me if it works in your settings.

Due to what could be a temporary problem with ngrok service, I was not able to test if there is a regression or not. Sorry for that.

**Comment by benel** [comment]
A side effect has just been fixed. The new container image (`aaaforrest:dev`) can be pulled for testing.

**Comment by christophe-lejeune** [comment]
This temporary container (with the fixed side effect) works for me ! Thanks to this code and configuration, users from different nodes can log in ! 

Thank you very much and congratulations for this great work !

**Comment by benel** [comment]
Great! 
The new container image is now published on DockerHub as `aaaforrest` (latest)!
